module.exports = [
  {
    title: 'JavaScript',
    description: 'JS Logo',
    rating: 10,
    url: 'http://devstickers.com/assets/img/pro/i4eg.png',
    user_id: 1,
  },
  {
    title: 'Rainbow JavaScript',
    description: 'JS Logo with Rainbow',
    rating: 10,
    url: 'http://devstickers.com/assets/img/pro/mw2g.png',
    user_id: 1,
  },
  {
    title: 'ES6',
    description: 'ES6 Logo',
    rating: 7,
    url: 'http://devstickers.com/assets/img/pro/i0dq.png',
    user_id: 1,
  },
  {
    title: 'JavaScript Beer',
    description: 'JS Beer Logo',
    rating: 7,
    url: 'http://devstickers.com/assets/img/pro/m539.png',
    user_id: 2,
  },
  {
    title: 'node.js hexagon',
    description: 'node.js hexagon logo',
    rating: 9,
    url: 'http://devstickers.com/assets/img/pro/iuw5.png',
    user_id: 2,
  },
  {
    title: 'node.js solid hexagon',
    description: 'node.js solid hexagon logo',
    rating: 8,
    url: 'http://devstickers.com/assets/img/pro/kh7x.png',
    user_id: 1,
  },
  {
    title: 'npm cube',
    description: 'npm logo in cube',
    rating: 6,
    url: 'http://devstickers.com/assets/img/pro/nrc3.png',
    user_id: 1,
  },
  {
    title: 'chai',
    description: 'chai.js logo',
    rating: 6,
    url: 'http://devstickers.com/assets/img/pro/5awx.png',
    user_id: 1,
  },
  {
    title: 'mocha',
    description: 'mocha.js logo',
    rating: 7,
    url: 'http://devstickers.com/assets/img/pro/4gem.png',
    user_id: 2,
  },
];
